### ISSUE TITLE
写了个python程序，根据json文件自动生成index.html

### ISSUE THREAD

**Issue by rhinoc** [WebStackPage/WebStackPage.github.io#10]
源码在[rhinoc/Index](https://github.com/rhinoc/Index)下generator文件夹。
另外推广一下我fork这个项目制作的导航[造作家](http://index.rhinoc.top)。

**Comment by bymori** [comment]
一个小白想问一下 没有什么基础  想要把后台搭上去 需要怎么操作呢？
可以探讨一下么？ 感谢

**Comment by ViggoZ** [comment]
> 源码在[rhinoc/Index](https://github.com/rhinoc/Index)下generator文件夹。
> 另外推广一下我fork这个项目制作的导航[造作家](http://index.rhinoc.top)。

已添加👍🏻

**Comment by ViggoZ** [comment]
> 一个小白想问一下 没有什么基础 想要把后台搭上去 需要怎么操作呢？
> 可以探讨一下么？ 感谢

查看最新的Readme文件，里面有写用哪个后台，也可以加QQ群聊
