### ISSUE TITLE
没有管理后台吗？

### ISSUE THREAD

**Issue by realzsy** [WebStackPage/WebStackPage.github.io#13]
没有管理后台吗？都是直接改index的源代码吗？
作者给出的后台文件，似乎还需要自己做搭建什么的，我们这种小白弄不来啊。

**Comment by JacobWang98** [comment]
没有后台的

**Comment by hanxi** [comment]
这里有个后台,挺不错的.我用 Docker 搭建的.
https://github.com/hui-ho/WebStack-Laravel

https://hub.docker.com/r/arvon2014/webstack-laravel

**Comment by fhefh2015** [comment]
@hanxi 老铁 666 我还准备自己写个来着 结果找Issue 竟然有 哈哈哈~
