### ISSUE TITLE
兄弟,您能在单文件中写这么多,是真的牛逼,我之后给你搞个 vue 版本的

### ISSUE THREAD

**Issue by xunyegege** [WebStackPage/WebStackPage.github.io#16]

**Comment by iceytea** [comment]
期待~ 希望能考虑到 SEO，和现有版本相比，Vue 貌似需要做额外的工作支持

**Comment by ViggoZ** [comment]
坐等啊兄弟！这个Issues就不关了，做好放项目链接啊

**Comment by ViggoZ** [comment]
顺便留下了没有技术的眼泪💦

**Comment by xunyegege** [comment]
放心吧兄弟,代码也许会迟到,但永远不会缺席.哈哈

**Comment by dahvlh** [comment]
催更大牛

**Comment by Mahoshojocn** [comment]
搞好了@我

**Comment by imjonat** [comment]
坐等！

**Comment by hustjiangtao** [comment]
我之前好像搞过vue版本的。。。不过我自己用了其他版本的就停在1.0版本了。。。

**Comment by ViggoZ** [comment]
@xunyegege 等你半年了，加油

**Comment by hustjiangtao** [comment]
vue的搞好了么？没搞的话，我准备把我的贡献出来了啊，顺便django的后台也一起拉出来了。之前这俩一起写的@xunyegege

**Comment by xunyegege** [comment]
期间经历了一些转岗事情,耽搁了,现在年底公司项目加更冲刺,还要耽搁些时日.让兄弟们久等了.不过看来大家对技术的渴望热情是满满的.棒👍

**Comment by xunyegege** [comment]
@hustjiangtao 可以的,兄弟搞起

**Comment by Anjaxs** [comment]
https://github.com/Anjaxs/WebStack-vue/tree/master  看那么久都没有人发出来，我就发下自己改的vue版本吧 @ViggoZ @Mahoshojocn @imjonat

**Comment by imjonat** [comment]
> https://github.com/Anjaxs/WebStack-vue/tree/master 看那么久都没有人发出来，我就发下自己改的vue版本吧 @ViggoZ @Mahoshojocn @imjonat

大佬🐮🍺，先star为敬

**Comment by ViggoZ** [comment]
> > https://github.com/Anjaxs/WebStack-vue/tree/master 看那么久都没有人发出来，我就发下自己改的vue版本吧 @ViggoZ @Mahoshojocn @imjonat
> 
> 大佬🐮🍺，先star为敬

感谢贡献，已收录👍
