### ISSUE TITLE
申请收录到“优秀项目示例”

### ISSUE THREAD

**Issue by jianrry** [WebStackPage/WebStackPage.github.io#27]
状态：已上线
网站名：Link - 我的网址收藏夹
网址：https://link.jianrry.com
预览：![https://link.jianrry.com](https://github.com/jianrry/link/raw/master/assets/images/screenshot.png)

**Comment by jianrry** [comment]
PS：顺便吐槽几点：

1.“优秀项目实例”里面已经有一部分网站下线了，比如说https://www.open985.com/ https://www.xmtbbx.com/ http://about.edu233.cn/ ，网站下线后不提交issues进行说明

2.还有一部分网站直接去掉了底部的版权信息，比如说http://www.yichushou.com/
https://www.avi101.com/ http://xxmap1.xyz/ http://miyue1980.com/ https://www.gezhipu.com/cn/index.html http://tool.wxuegao.com/ http://vv.lc/ https://fusfun.club

3.还有一部分网站改用了其他项目，与这个项目完全无关了，也不提交issues进行说明

4.这里面还收录了2个XX导航，http://xxmap1.xyz/ https://www.avi101.com/ ...

**Comment by ViggoZ** [comment]
已经添加了哈，其他下线的也都处理了，多谢🙏最近比较忙
