### ISSUE TITLE
写了个从Chrome书签生成Jekyll版本配置的工具

### ISSUE THREAD

**Issue by hanxi** [WebStackPage/WebStackPage.github.io#45]
体验网址： https://w.hanxi.info/convert.html

- 没有使用书签中存放的 16x16 的logo，太小了，放进来非常模糊
- logo 是使用 https://github.com/mat/besticon 自动拉取或者生成的
- logo 生成失败则采用 title 首字作为 logo
- 由于书签中只有 title，没想到比较好的切分出 title 和 description 的方法，就只显示 title 了
- 转出的效果： https://w.hanxi.info

欢迎Star https://github.com/hanxi/webstack-jekyll

**Comment by ViggoZ** [comment]
已经收录 厉害 赞

**Comment by hanxi** [comment]
👍
