### ISSUE TITLE
缩小导航栏时的一些问题

### ISSUE THREAD

**Issue by sufanx** [WebStackPage/WebStackPage.github.io#8]
1. "关于本站"的显示不太友好
2.  页面滑动时,导航栏并没有固定,而是随着页面一起滚动
![snipaste_2019-01-07_13-11-53](https://user-images.githubusercontent.com/18508263/50750068-d6795a80-127d-11e9-94c1-f52738fe8f16.png)

另外一些觉得不太好的地方:
1. 返回顶部的按钮位置并不是太友好,不应该仅仅是在底部才有返回顶部按钮
2. 响应式页面在某些size下,导航栏相对于正文的布局并不是太合理

**Comment by rhinoc** [comment]
```html
<a href="about.html">
    <i class="linecons-doc"></i>
    <span class="title">关于本站</span>
</a>
```
很早之前改的，具体的操作忘记了。
把「关于本站」放到和前面菜单项目同级元素内。

**Comment by ViggoZ** [comment]
多谢多谢～这些小的体验点可能我也没有时间去修理，兄弟们自由发挥～
